# Generated by Django 3.0.6 on 2020-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200611_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='TimeEnd',
            field=models.DateTimeField(null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='TimeStart',
            field=models.DateTimeField(null=True, verbose_name='time'),
        ),
    ]
