# Generated by Django 3.0.6 on 2020-06-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200611_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Saftey',
            new_name='Safety',
        ),
    ]
