# Generated by Django 3.0.6 on 2020-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200611_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Safety',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='WitnessProtection',
            field=models.BooleanField(null=True),
        ),
    ]
