# Generated by Django 3.0.6 on 2020-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_game_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ExtraRules',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='KillMethod',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='SafetyZones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='TimeEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='TimeStart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='WitnessProtection',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
