# Generated by Django 3.0.6 on 2020-06-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20200612_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deathConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='killConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='targetID',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
