# Generated by Django 3.0.6 on 2020-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20200613_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='killedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='targetID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
