# Generated by Django 3.0.6 on 2020-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_user_kills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='SafetyZones',
            new_name='SafetyCircumstances',
        ),
        migrations.AlterField(
            model_name='game',
            name='Safety',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
