# Generated by Django 3.0.6 on 2020-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20200616_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='contactInfo',
            new_name='otherContactInfo',
        ),
        migrations.AddField(
            model_name='game',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
