# Generated by Django 3.0.6 on 2020-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20200619_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='killCam',
            field=models.BooleanField(default=True),
        ),
    ]
