# Generated by Django 3.0.6 on 2020-07-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_game_killcam'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killID', models.IntegerField(blank=True, null=True)),
                ('killerID', models.IntegerField(default=0)),
                ('killedID', models.IntegerField(default=0)),
                ('gameID', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='compilationDone',
            field=models.BooleanField(default=False),
        ),
    ]
