# Generated by Django 3.0.6 on 2020-07-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20200703_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='killvideo',
            name='killConf',
            field=models.BooleanField(default=False),
        ),
    ]
