# Generated by Django 3.0.6 on 2020-08-31 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_killvideo_usable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('KD', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('mods', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=True)),
                ('kills', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
