# Generated by Django 3.1.6 on 2021-03-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
