# Generated by Django 4.0 on 2021-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_game_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='teamID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
