# Generated by Django 4.0 on 2021-12-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_team_game_teams_player_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.IntegerField(default=1),
        ),
    ]
