# Generated by Django 4.0 on 2021-12-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_alter_game_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='randomTeams',
            field=models.BooleanField(default=False),
        ),
    ]
