# Generated by Django 4.0 on 2021-12-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_team_targetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
