# Generated by Django 4.0 on 2022-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_game_extrauserinfostring_player_extrainfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='KillMethod',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
