# Generated by Django 4.0 on 2022-07-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_alter_game_killmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='gameString',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
